name: m_d_template_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3

  #: TODO: Add firebase plugins
  #: 1- uncomment in pubspec.yaml
  #: 2- uncomment in android/build.gradle
  #: 3- uncomment in android/app/build.gradle
  #: 4- uncomment in main_common.dart
  #: 5- uncomment in analytics_service.dart
  #: 6- add google-services.json file to android/app/
  #: 7- add GoogleService-Info.plist file to ios/Runner/

  # # Firebase
  # firebase_core: ^3.8.0
  # firebase_auth: ^5.3.3
  # firebase_analytics: ^11.3.5
  # firebase_messaging: ^15.1.5
  # firebase_crashlytics: ^4.1.5
  # firebase_performance: ^0.10.0+10
  # firebase_dynamic_links: ^6.0.10
  # firebase_remote_config: ^5.1.5

  flutter_screenutil: ^5.9.3
  universal_platform: ^1.0.0+1

  connectivity_plus: ^5.0.2

  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4


  gap: ^3.0.1

  upgrader: ^11.3.1


  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:

flutter:
 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
 
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Lato-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
# when change any images, you need to run this command
# (dart run build_runner build)
flutter_gen:
  integrations:
    flutter_svg: true

# when change any images, you need to run this command
# (dart run flutter_launcher_icons)
flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path_ios: "assets/images/logo.jpg"
  image_path: "assets/images/logo.jpg" # Path to your icon image
  adaptive_icon_foreground: "assets/images/logo.jpg" # Path to foreground image
  # adaptive_icon_background: "#162B45" # Change this to your desired color code
